// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Config {
    "host": string;
    "port": number;
    "downloadDir": string;
    "downloadRate": number;
    "uploadRate": number;
    "maxConnections": number;
    "noDHT": boolean;
    "disableIPv6": boolean;
    "disableUTP": boolean;
    "storageType": string;
    "memorySize": number;
    "tmdbKey": string;
    "openSubtitlesUser": string;
    "openSubtitlesPassword": string;
    "openSubtitlesKey": string;
    "torznabFeeds": TorznabFeed[] | null;
    "ncoreUser": string;
    "ncorePassword": string;
    "insaneUser": string;
    "insanePassword": string;
}

export interface TorznabFeed {
    "url": string;
    "apiKey": string;
}
