// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Config {
    "host": string;
    "port": number;
    "dlnaPort": number;
    "downloadDir": string;
    "downloadRate": number;
    "uploadRate": number;
    "maxConnections": number;
    "noDHT": boolean;
    "storageType": string;
    "memorySize": number;
    "tmdbKey": string;
    "openSubtitlesUser": string;
    "openSubtitlesPassword": string;
    "openSubtitlesKey": string;
    "jackettAddress": string;
    "jackettKey": string;
    "ncoreUser": string;
    "ncorePassword": string;
    "insaneUser": string;
    "insanePassword": string;
}
