// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as runtime$0 from "../server/runtime/models.js";

export interface RootedInstallRequest {
    "host": string;
    "port": number;
    "username": string;
    "password": string;
    "reboot": boolean;
    "config": runtime$0.Config;
}

export interface WidgetStatus {
    "busy": boolean;
    "syncRunning": boolean;
    "mode": string;
    "message": string;
    "version": string;
    "address": string;
}
