// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as runtime$0 from "../server/runtime/models.js";

export interface RootedInstallRequest {
    "host": string;
    "port": number;
    "username": string;
    "password": string;
    "installServer": boolean;
    "reboot": boolean;
    "config": runtime$0.Config;
}

/**
 * UpdateStatus describes the update flow state for the frontend: whether
 * updates are available on this build, the running version, the platform
 * (so the frontend can pick the right download flow), the updater's current
 * lifecycle phase, and the pending release version (if any).
 */
export interface UpdateStatus {
    "enabled": boolean;
    "currentVersion": string;
    "platform": string;
    "state": string;
    "version": string;
}

export interface WidgetStatus {
    "busy": boolean;
    "syncRunning": boolean;
    "mode": string;
    "message": string;
    "version": string;
    "address": string;
}
