// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as runtime$0 from "../server/runtime/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ClearLogs(): $CancellablePromise<void> {
    return $Call.ByID(1494630468);
}

export function DefaultConfig(): $CancellablePromise<runtime$0.Config> {
    return $Call.ByID(682358145);
}

export function InstallRooted(request: $models.RootedInstallRequest): $CancellablePromise<void> {
    return $Call.ByID(1041141100, request);
}

export function LoadConfig(): $CancellablePromise<runtime$0.Config> {
    return $Call.ByID(239334184);
}

export function Logs(): $CancellablePromise<string> {
    return $Call.ByID(3825520965);
}

export function SaveConfig(config: runtime$0.Config): $CancellablePromise<void> {
    return $Call.ByID(1985109641, config);
}

export function Shutdown(): $CancellablePromise<void> {
    return $Call.ByID(1644381792);
}

export function StartAppSync(): $CancellablePromise<void> {
    return $Call.ByID(1128248954);
}

export function StartServer(config: runtime$0.Config): $CancellablePromise<void> {
    return $Call.ByID(1233440937, config);
}

export function Status(): $CancellablePromise<runtime$0.Status> {
    return $Call.ByID(1166105408);
}

export function StopAppSync(): $CancellablePromise<void> {
    return $Call.ByID(1941000114);
}

export function StopServer(): $CancellablePromise<void> {
    return $Call.ByID(1048709617);
}

export function WidgetStatus(): $CancellablePromise<$models.WidgetStatus> {
    return $Call.ByID(2264255148);
}
